name: mighty_fitness
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Basic
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0

  # Network
  http: ^1.2.1
  connectivity_plus: ^5.0.2

  # State Management
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # Storage
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.9.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.1.2
  firebase_auth: ^5.3.0

  # Login
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  # OneSignal
  onesignal_flutter: ^5.1.0

  # Notification
  awesome_notifications: ^0.9.2

  # Video Player
  youtube_player_flutter: ^9.0.4
  chewie: ^1.7.5
  #better_player : ^0.0.84

  # Ads
  # google_mobile_ads: ^3.0.0

  # Step Count
  pedometer: ^4.0.1

  # GPT
  chat_gpt_flutter: ^1.0.16

  # Other
  fluttertoast: ^8.2.4
  country_code_picker: ^3.0.0
  infinite_listview: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  flutter_html:
    git:
      url: https://github.com/cgs/flutter_html
      ref: alpha-6-flutter-322
  flutter_tts: ^3.8.5
  draggable_bottom_sheet: ^1.0.2
  share_plus: ^7.2.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_bounce: ^1.1.0
  card_swiper: ^3.0.1
  simple_pip_mode: ^0.8.0
  photo_view: ^0.14.0

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Chart
  syncfusion_flutter_charts: ^26.2.14
  path_provider: ^2.1.2

  # Payment
  flutter_stripe: ^10.0.0
  flutter_braintree: ^3.0.0
  # flutterwave_standard: ^1.0.8
  flutter_paytabs_bridge: ^2.6.7
  in_app_purchase: ^3.2.0

  flutter_image_compress: ^1.1.0
  camera: ^0.10.0+1

  fl_chart: ^1.0.0
  table_calendar: ^3.0.9


dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.5
  # flutter_html: ^2.2.1
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.5
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/
    - assets/ca/lets-encrypt-r3.pem
